#!/bin/bash
# regenerate drupal5 mysql password

PASSWORD=$(mcookie)

CONF=/etc/drupal/5/sites/default/dbconfig.php
sed -i "s/\$dbpass=\(.*\)/\$dbpass=\'$PASSWORD\';/" $CONF

CONF=/etc/dbconfig-common/drupal5.conf
sed -i "s/dbc_dbpass=\(.*\)/dbc_dbpass=\'$PASSWORD\'/" $CONF

/usr/lib/di-live.d/??mysql-conf -u drupal5 -p $PASSWORD --chroot=/

